jobs:
  install_node:
    docker:
      - image: cimg/node:12.18.4
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
orbs:
  node: circleci/node@3.0.0
workflows:
  version: 2.1
  circle_ci_test:
    jobs:
      - install_node
      - test
