jobs:
  install-dependencies:
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit_tests:
    description: Run unit tests
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: Run unit tests
          command: yarn run test
orbs:
  node: circleci/node@3.0.0
version: 2.1
workflows:
  circle_ci_test:
    jobs:
      - install-dependencies
      - unit_tests:
          requires:
            - install-dependencies
