jobs:
  install-dependencies:
    docker:
      - image: cimg/node:12.18.4
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  unit_tests:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
orbs:
  node: circleci/node@3.0.0
version: 2.1
workflows:
  circle_ci_test:
    jobs:
      - install-dependencies
      - unit_tests:
          requires:
            - install-dependencies
